/* mdliteHtml must emit byte-identical HTML to the vanilla UI's mdLite()
   (ui/shim.js). The vectors were generated by running the vanilla function
   itself — regenerate with the snippet in the repo history if mdLite gains
   syntax. */

import { describe, expect, it } from "vitest";
import { mdliteHtml, esc } from "../src/lib/mdliteHtml";
import vectors from "./mdlite-vectors.json";

describe("mdliteHtml parity with ui/shim.js mdLite", () => {
  for (const [input, expected] of vectors as [string, string][]) {
    it(JSON.stringify(input.slice(0, 40)), () => {
      expect(mdliteHtml(input)).toBe(expected);
    });
  }
});

describe("esc", () => {
  it("escapes the five specials", () => {
    expect(esc(`<a href="x">&'`)).toBe("&lt;a href=&quot;x&quot;&gt;&amp;&#39;");
  });
  it("stringifies null/undefined to empty", () => {
    expect(esc(null)).toBe("");
    expect(esc(undefined)).toBe("");
  });
});
