/* Golden-vector tests for mdliteHtml. The vectors in mdlite-vectors.json
   were generated by running the original mdLite() from the retired vanilla
   UI (ui/shim.js in the repo history), so this HTML dialect stays stable
   even though that implementation is gone. */

import { describe, expect, it } from "vitest";
import { mdliteHtml, esc } from "../src/lib/mdliteHtml";
import vectors from "./mdlite-vectors.json";

describe("mdliteHtml golden vectors", () => {
  for (const [input, expected] of vectors as [string, string][]) {
    it(JSON.stringify(input.slice(0, 40)), () => {
      expect(mdliteHtml(input)).toBe(expected);
    });
  }
});

describe("esc", () => {
  it("escapes the five specials", () => {
    expect(esc(`<a href="x">&'`)).toBe("&lt;a href=&quot;x&quot;&gt;&amp;&#39;");
  });
  it("stringifies null/undefined to empty", () => {
    expect(esc(null)).toBe("");
    expect(esc(undefined)).toBe("");
  });
});
