#!/usr/bin/env bash
set -euo pipefail

die() {
  echo "worktree: $*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  scripts/worktree.sh new <branch> [--from <ref>] [--copy-env] [--install-deps]
  scripts/worktree.sh list
  scripts/worktree.sh rm <branch-or-path> [--delete-branch]

Creates isolated feature worktrees under .worktrees/. The command does not
fetch; use --from to select an offline/local starting ref when necessary.
EOF
}

git rev-parse --show-toplevel >/dev/null 2>&1 || die "run this inside an Agora checkout"
common_dir=$(git rev-parse --path-format=absolute --git-common-dir)
main_root=$(dirname "$common_dir")
worktrees_dir="$main_root/.worktrees"

slug_for() {
  printf '%s' "$1" | tr '/' '-' | sed 's/[^A-Za-z0-9._-]/-/g'
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

link_skills() {
  local worktree=$1 rel source target
  for rel in .claude/skills mobile/.claude/skills .codex/skills mobile/.codex/skills; do
    source="$main_root/$rel"
    target="$worktree/$rel"
    if [[ -d "$source" && ! -e "$target" && ! -L "$target" ]]; then
      mkdir -p "$(dirname "$target")"
      ln -s "$source" "$target"
    fi
  done
}

reserve_slot_and_write_env() {
  local worktree=$1 slug=$2
  local lock="$worktrees_dir/.slot-lock" lock_q attempts=0 slot=1 env_file used
  while ! mkdir "$lock" 2>/dev/null; do
    attempts=$((attempts + 1))
    (( attempts < 100 )) || die "timed out waiting for the port-slot lock; if no other run is active, remove $lock"
    sleep 0.1
  done
  printf -v lock_q '%q' "$lock"
  trap "rmdir $lock_q 2>/dev/null || true" RETURN EXIT INT TERM
  while :; do
    used=false
    for env_file in "$worktrees_dir"/*/.worktree-env; do
      [[ -f "$env_file" ]] || continue
      if grep -q "^export AGORA_WORKTREE_SLOT=$slot$" "$env_file"; then
        used=true
        break
      fi
    done
    [[ "$used" == false ]] && break
    slot=$((slot + 1))
  done
  write_env "$worktree" "$slug" "$slot"
  printf '%s' "$slot"
}

write_env() {
  local worktree=$1 slug=$2 slot=$3
  local server_port=$((4470 + slot * 10))
  local web_port=$((5173 + slot * 10))
  local storybook_port=$((6006 + slot * 10))
  local metro_port=$((8081 + slot * 10))
  local data_dir="/tmp/agora-$slug"
  local cargo_target="$worktree/.cargo-target"
  {
    echo "# Generated by scripts/worktree.sh; source this file for each command."
    echo "export AGORA_WORKTREE_SLOT=$slot"
    echo "export AGORA_PORT=$server_port"
    echo "export AGORA_WEB_PORT=$web_port"
    echo "export AGORA_STORYBOOK_PORT=$storybook_port"
    echo "export AGORA_METRO_PORT=$metro_port"
    printf 'export AGORA_BASE=%s\n' "$(shell_quote "http://127.0.0.1:$server_port")"
    printf 'export AGORA_DATA_DIR=%s\n' "$(shell_quote "$data_dir")"
    printf 'export CARGO_TARGET_DIR=%s\n' "$(shell_quote "$cargo_target")"
  } > "$worktree/.worktree-env"
  chmod 600 "$worktree/.worktree-env"
}

new_worktree() {
  [[ $# -ge 1 ]] || die "new requires a branch name"
  local branch=$1 from_ref="" copy_env=false install_deps=false
  shift
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --from)
        [[ $# -ge 2 ]] || die "--from requires a ref"
        from_ref=$2
        shift 2
        ;;
      --copy-env) copy_env=true; shift ;;
      --install-deps) install_deps=true; shift ;;
      *) die "unknown new option: $1" ;;
    esac
  done

  git check-ref-format --branch "$branch" >/dev/null 2>&1 || die "invalid branch name: $branch"
  mkdir -p "$worktrees_dir"
  local slug target
  slug=$(slug_for "$branch")
  target="$worktrees_dir/$slug"
  [[ ! -e "$target" ]] || die "target already exists: $target"

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    [[ -z "$from_ref" ]] || echo "worktree: warning: --from is ignored because local branch '$branch' already exists" >&2
    if ! git worktree add "$target" "$branch"; then
      die "could not attach '$branch'; it may already be checked out in another worktree"
    fi
  elif git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
    [[ -z "$from_ref" ]] || echo "worktree: warning: --from is ignored because origin/$branch already exists" >&2
    git worktree add --track -b "$branch" "$target" "origin/$branch"
  else
    if [[ -z "$from_ref" ]]; then
      if git rev-parse --verify --quiet origin/main >/dev/null; then
        from_ref=origin/main
      elif git rev-parse --verify --quiet main >/dev/null; then
        from_ref=main
      else
        from_ref=HEAD
      fi
    fi
    git rev-parse --verify --quiet "$from_ref^{commit}" >/dev/null || die "starting ref does not exist: $from_ref"
    git worktree add -b "$branch" "$target" "$from_ref"
  fi

  local slot
  slot=$(reserve_slot_and_write_env "$target" "$slug")
  link_skills "$target"

  if [[ "$copy_env" == true && -f "$main_root/.env" ]]; then
    cp "$main_root/.env" "$target/.env"
    chmod 600 "$target/.env"
  fi
  if [[ "$install_deps" == true ]]; then
    (cd "$target" && npm ci)
  fi

  echo "Created $target on branch $branch (port slot $slot)."
  echo "Start commands with: source .worktree-env && ..."
}

list_worktrees() {
  git worktree list
}

remove_worktree() {
  [[ $# -ge 1 ]] || die "rm requires a branch or path"
  local requested=$1 delete_branch=false
  shift
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --delete-branch) delete_branch=true; shift ;;
      *) die "unknown rm option: $1" ;;
    esac
  done

  local target="" branch="" path="" ref=""
  while IFS= read -r line; do
    case "$line" in
      worktree\ *) path=${line#worktree } ;;
      branch\ *)
        ref=${line#branch refs/heads/}
        if [[ "$requested" == "$path" || "$requested" == "$ref" || "$requested" == "$(basename "$path")" ]]; then
          target=$path
          branch=$ref
        fi
        ;;
      '')
        if [[ -z "$target" && "$requested" == "$path" ]]; then target=$path; fi
        path=""
        ref=""
        ;;
    esac
  done < <(git worktree list --porcelain; echo)

  [[ -n "$target" ]] || die "not a registered worktree: $requested"
  [[ "$target" != "$main_root" ]] || die "refusing to remove the main checkout"
  [[ -z "$(git -C "$target" status --porcelain)" ]] || die "worktree is dirty; commit or remove its changes first: $target"
  git worktree remove "$target"
  git worktree prune
  if [[ "$delete_branch" == true ]]; then
    [[ -n "$branch" ]] || die "cannot delete a detached worktree branch"
    git branch -d "$branch"
  fi
  echo "Removed $target."
}

command=${1:-}
case "$command" in
  new) shift; new_worktree "$@" ;;
  list) shift; [[ $# -eq 0 ]] || die "list takes no arguments"; list_worktrees ;;
  rm) shift; remove_worktree "$@" ;;
  -h|--help|help) usage ;;
  *) usage >&2; exit 1 ;;
esac
